module.exports = {
    gpks1: {
        '1a': 'Nasty Nick',
        '1b': 'Evil Eddie',
        '2a': 'Junkfood John',
        '2b': 'Ray Decay',
        '3a': 'Up Chuck',
        '3b': 'Heavin\' Steven',
        '4a': 'Fryin\' Brian',
        '4b': 'Electric Bill',
        '5a': 'Dead Ted',
        '5b': 'Jay Decay',
        '6a': 'Art Apart',
        '6b': 'Busted Bob',
        '7a': 'Stormy Heather',
        '7b': 'April Showers',
        '8a': 'Adam Bomb',
        '8b': 'Blasted Billy',
        '9a': 'Boozin\' Bruce',
        '9b': 'Drunk Ken',
        '10a': 'Tee-Vee Stevie',
        '10b': 'Geeky Gary',
        '11a': 'Itchy Richie',
        '11b': 'Bugged Bert',
        '12a': 'Furry Fran',
        '12b': 'Hairy Mary',
        '13a': 'Ashcan Andy',
        '13b': 'Spacey Stacy',
        '14a': 'Potty Scotty',
        '14b': 'Jason Basin',
        '15a': 'Ailin\' Al',
        '15b': 'Mauled Paul',
        '16a': 'Weird Wendy',
        '16b': 'Haggy Maggie',
        '17a': 'Wacky Jackie',
        '17b': 'Loony Lenny',
        '18a': 'Cranky Frankie',
        '18b': 'Bad Brad',
        '19a': 'Corroded Carl',
        '19b': 'Crater Chris',
        '20a': 'Swell Mel',
        '20b': 'Dressy Jesse',
        '21a': 'Virus Iris',
        '21b': 'Sicky Vicky',
        '22a': 'Junky Jeff',
        '22b': 'Stinky Stan',
        '23a': 'Drippy Dan',
        '23b': 'Leaky Lou',
        '24a': 'Nervous Rex',
        '24b': 'Nerdy Norm',
        '25a': 'Creepy Carol',
        '25b': 'Scary Carrie',
        '26a': 'Slobby Robbie',
        '26b': 'Fat Matt',
        '27a': 'Brainy Janie',
        '27b': 'Jenny Genius',
        '28a': 'Oozy Suzy',
        '28b': 'Meltin\' Melissa',
        '29a': 'Bony Joanie',
        '29b': 'Thin Lynn',
        '30a': 'New Wave Dave',
        '30b': 'Graffiti Petey',
        '31a': 'Run Down Rhoda',
        '31b': 'Flat Pat',
        '32a': 'Frigid Bridget',
        '32b': 'Chilly Millie',
        '33a': 'Mad Mike',
        '33b': 'Savage Stuart',
        '34a': 'Kim Kong',
        '34b': 'Anna Banana',
        '35a': 'Wrinkly Randy',
        '35b': 'Rockin\' Robert',
        '36a': 'Wrappin\' Ruth',
        '36b': 'Tommy Tomb',
        '37a': 'Guillo Tina',
        '37b': 'Cindy Lopper',
        '38a': 'Slimy Sam',
        '38b': 'Lizard Liz',
        '39a': 'Buggy Betty',
        '39b': 'Green Jean',
        '40a': 'Unstiched Mitch',
        '40b': 'Damaged Don',
        '41a': 'Mean Gene',
        '41b': 'Joltin\' Joe',
    },
    exotic: {
        '1a': 'Joe Chaotic',
        '1b': 'Schmo Exotic',
        '2a': 'Jettin\' James',
        '2b': 'Gangsta\' Garretson',
        '3a': 'Jeff Joke',
        '3b': 'Lowe Point',
        '4a': 'Cool Cat Carole',
        '4b': 'Batty Baskin',
        '5a': 'Disturbing Doc',
        '5b': 'Party Animal Antle',
        '6a': 'Humiliated Howard',
        '6b': 'Bruised Ego Baskin',
        '7a': 'Roasted Rick',
        '7b': 'Kindled Kirkham',
        '8a': 'Allen Assassin',
        '8b': 'Gunman Glover',
        '9a': 'Lenient Lauren',
        '9b': 'Lowe Standards',
        '10a': 'Jazzy Joe',
        '10b': 'Toxic Exotic',
        '11a': 'Ortho-John-Tist',
        '11b': 'Tooth Fairy Finlay',
        '12a': 'Political Junkie Joshua',
        '12b': 'Don\'t Vote Dial',
        '13a': 'Savage Saff',
        '13b': 'Spiteful Saffery',
        '14a': 'Nutty Nicolas',
        '14b': 'Tiger Cage',
        '15a': 'Ty Grrr',
        '15b': 'Lounging Leo'
    }
}
